### ISSUE TITLE
Issue with the signup process

### ISSUE THREAD

**Issue by Rcc999** [Swent-Fall-2024-team-10/leazy#111]
Looking into the code, and the navigation in the particular, I raised some potential issues. First, the fact that when we sign up, we are choosing an email and password for tenant and landlord, which put us in a logged in state and give us access to the homedrawer and home stack. We do that before filling the form, which is wrong and prone to issues (like the one of accessing the side bar during the profile form filling). 

Also i remarked that we merged something wrong to the main, its the code written in the index.tsx (the main one with all the nvigation logic). The thing that may cause access to the side bar may come from the fact that we putted the navigation logic of the  CodeEntry, Code Approved and TenantForm into the Root Navigator. Personally I think it should be in the AuthStackNavigator. 

We will have to discuss that to resolve these issues

**Comment by baudoin-csp** [comment]
Hey Rayane!

I checkout to your branch and can confirm that there is an issue regarding sign up. I tried to move the CodeEntry, Code Approved and TenantForm screen into the auth navigator but it doesn't work as expected. I think @MadelineDesautel worked on this part at the beginning of the project, maybe we can set a quick meeting to understand how to fix this issue together.
