### ISSUE TITLE
figma design v1

### ISSUE THREAD

**Issue by userdarius** [Swent-Fall-2024-team-10/leazy#25]
We submit a proposal for designing the figma for the leazy app. The first version of the figma implements the renter / manager issue and maintenance reporting. This issue is a recap of the work we have done and provides a link to the figma project and a more thorough description in the wiki.

**Comment by baudoin-csp** [comment]
I'll add some pictures of our work as the wiki may change in the future.

<div style="display: flex; gap: 10px;">
    <img src="https://github.com/user-attachments/assets/d0e62acb-8650-4453-af91-195e85af5310" width="600">
    <img src="https://github.com/user-attachments/assets/6b35d918-34ca-4033-a7e0-f03396022ad8" width="800">
</div>

<div style="display: flex; gap: 10px;">
    <img src="https://github.com/user-attachments/assets/87d10dce-8c86-454f-89f3-4da50cfe13a5" width="800">
    <img src="https://github.com/user-attachments/assets/25ee7909-4d2d-42e1-b109-9d4438ade0f5" width="300">
</div>

<img width="800" alt="Screenshot 2024-10-17 at 10 28 32" src="https://github.com/user-attachments/assets/69f06d3d-40cf-43f4-84fb-afafc5ab8291">
