### ISSUE TITLE
Fix : Add a listener to the db to fetch the issues

### ISSUE THREAD

**Issue by AdrienDeschenaux** [Swent-Fall-2024-team-10/leazy#66]
Currently the issues are only fetch when we enter the issue route, but we need to have a listener or some other implementation such that the issue list is updated when a modification is made on an issue so that the tenant issue list is always up to date

Maybe first we can only update when a new issue is added and it can be implemented later that when a issue is modified we also have a new update of the issue list (maybe only fetch the updated issue)

**Comment by mdesautel** [comment]
Done using onSnapshot in useEffect() and with a new method in the ViewModel file (firestore.ts) that fetches all requests for a given tenant in the form of a query (needed for the onSnapshot listener).
