### ISSUE TITLE
Bug: Application Crashes When Taking Multiple Pictures in a Row

### ISSUE THREAD

**Issue by AdrienDeschenaux** [Swent-Fall-2024-team-10/leazy#67]
**Issue**:  
The application crashes when users take multiple pictures in a row. This is likely due to the fact that the names of the pictures are not unique, causing conflicts when saving multiple images with the same filename.

**Proposed Solution**:  
To resolve this issue, we need to implement the following steps:
1. **Generate Unique Picture Names**: Ensure that each picture taken has a unique name, possibly by incorporating timestamps, unique IDs, or a combination of both.
2. **Test for Name Uniqueness**: Verify that taking multiple pictures in quick succession generates distinct filenames to avoid any overwriting or conflicts.
3. **Update Picture List Properly**: Confirm that the picture list is updated correctly with the unique URLs for each image, ensuring that all images are displayed and accessible after they are taken.

**Expected Outcome**:  
- The application no longer crashes when taking multiple pictures in a row.
- All pictures are saved with unique filenames and appear correctly in the picture list with their respective URLs.

**Comment by mdesautel** [comment]
done! The problem came from the fact that the images were too large to be stored simultaneously, so now they are resized and compressed a little before their uploading!
